plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - - '@semantic-release/exec'
    - prepareCmd: 'oclif-dev manifest && oclif-dev readme --dir docs/ --multi && yarn prettify'
  - - '@semantic-release/git'
    - assets:
       - "docs"
       - "package.json"
       - 'README.md'
       - 'CHANGELOG.md'
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - '@semantic-release/github'
